class Map(object):

	def displayMap(self):

		print("                                                      ")
		print("                   MAP                                ")
		print("                                                      ")
		print("               +--------+							 ")                             
		print("          +----+        |                             ")
		print("          |    |        +------+                      ")
		print("          |    X Library|      |                      ")
		print("          |    X        X Dragon                      ")
		print("          |    |        X      |                      ")
		print("          |    +---------+-XX-++----+                 ")
		print("          |    |         |    X Pit |                 ")
		print("          |    |         |    X     |                 ")
		print("          |    |         |    +-----+                 ")
		print("          |    |         |    |                       ")
		print("          |    +---------+    |                       ")
		print("          |    |         |    |                       ")
		print("          |    X Dungeon X    |                       ")
		print("       Hallway |         | Tunnel                     ")
		print("          |    +---------+    |                       ")
		print("          |    |         |    |                       ")
		print("          |    |         |    |                       ")
		print("          |    |         |    |                       ")
		print("          |    |         +----+                       ")
		print("          |    |                                      ")
		print("          |    |                                      ")
		print("   +------+-XX-+-+                     +-------------+")
		print("   |    X        +---------------------+             |")
		print("   |    X Dining X     Windy tunnel    X   Kitchen   |")
		print("   |    X  Room  +---------------------+             |")
		print("   |    +--------+                     +---+-XXX-+---+")
		print("   |    |                                  | Key |    ")
		print("   |    |                                  | Room|    ")
		print("  Ballroom                                 +-----+    ")
		print("   |    |                                             ")
		print("   |    |                                             ")
		print("+--+-XX-+--+                                          ")
		print("|          |                                          ")
		print("Entranceway|                                          ")
		print("|          |                                          ")
		print("+---XXX----+                                          ")
		print("")